name: Deploy to Netlify on release
on: push
env:
  SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install Node
        uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: Install Dependencies
        run: yarn install

      - name: Build site
        run: yarn build

      - name: Deploy Site
        env:
          NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID }}
          NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
        run: netlify deploy --dir=build --prod
      - name: Create Slack notification
        if: always()
        uses: edge/simple-slack-notify@master
        with:
          channel: '#pat-lib-notifications'
          status: ${{ job.status }}
          success_text: 'Successfully deployed release to Netlify'
          failure_text: 'Failed deployed release to Netlify'
          cancelled_text: 'Deploy to Netlify was cancelled'
          fields: |
            [{ "title": "Action", "value": "${env.GITHUB_WORKFLOW} - build (${env.GITHUB_RUN_NUMBER})", "short": true },
            { "title": "Repository", "value": "${env.GITHUB_REPOSITORY}", "short": true },
            { "title": "By", "value": "${{ github.actor }}"},
            { "title": "View job", "value": "${env.GITHUB_SERVER_URL}/${env.GITHUB_REPOSITORY}/actions/runs/${env.GITHUB_RUN_ID}"}]
